server {
    listen 8080;
    root /usr/share/nginx/html;
    index index.html;

    location /admin/ {
        try_files $uri $uri/ /index.html;
    }

    location = /admin {
        return 301 /admin/;
    }
}
